project_id = "dqszicdrfcmwkutviayw"

[functions.ai-chat]
verify_jwt = false

[functions.ai-auto-score]
verify_jwt = false

[functions.creative-concept]
verify_jwt = false

[functions.creative-image]
verify_jwt = false

[functions.landing-strategy]
verify_jwt = false

[functions.landing-structure]
verify_jwt = false

[functions.landing-image]
verify_jwt = false
